locations = ["dhaka", "rajshahi", "kazla", "zero point", "binodpur bazar"]
print(locations)
print(sorted(locations))
print(locations)
locations.reverse()
print(locations)
locations.reverse()
print(locations)
locations.reverse()
print(locations)

locations.sort()
print(locations)
locations.sort(reverse=True)
print(locations)