-- 1. Show list of Employees who got salary less than Employee id 144
SELECT * FROM EMPLOYEES;

SELECT *
FROM EMPLOYEES
WHERE SALARY < (
				SELECT SALARY
				FROM EMPLOYEES
				WHERE EMPLOYEE_ID = 144
				);

-- 2. SHOW THE RECORD WHO GOT HEIGHT SALARY
SELECT *
FROM EMPLOYEES
WHERE SALARY = (
				SELECT MAX(SALARY)
				FROM EMPLOYEES
				);
                
-- 3. i. SHOW LIST OF MARKETING DEPARTMENT EMPLOYEES
SELECT *
FROM EMPLOYEES
WHERE DEPARTMENT_ID = (
				SELECT DEPARTMENT_ID
				FROM DEPARTMENTS
                WHERE DEPARTMENT_NAME = 'MARKETING'
				);
                
-- 3. ii SHOW AVARAGE SALARY OF MARKETING DEPARTMENT EMPLOYEES
SELECT AVG(SALARY)
FROM EMPLOYEES
WHERE DEPARTMENT_ID = (
				SELECT DEPARTMENT_ID
				FROM DEPARTMENTS
                WHERE DEPARTMENT_NAME = 'MARKETING'
				);
                
-- 4. HOW MANY EMPLOYEES DOING JOB IN IT DEPARTMENT?
SELECT COUNT(*) AS IT_MEMBERS
FROM EMPLOYEES
WHERE DEPARTMENT_ID = (
				SELECT DEPARTMENT_ID
				FROM DEPARTMENTS
                WHERE DEPARTMENT_NAME = 'IT'
				);
                
-- 5. HOW MUCH GOT PROGRAMMERS IN EACH MONTH?
SELECT SUM(SALARY)
FROM EMPLOYEES
WHERE JOB_ID = (
				SELECT JOB_ID
				FROM JOBS
                WHERE JOB_TITLE = 'PROGRAMMER'
				);