SELECT AVG(SALARY)
FROM EMPLOYEES
WHERE DEPARTMENT_ID = 60; -- IT

SELECT MAX(SALARY)
FROM EMPLOYEES
WHERE DEPARTMENT_ID = 20; -- MARKETING

-- SHOW THE LIST WHO'S SALARY IS MORE THAN FROM IT DEPARTMENT AVARAGE SALARY, BUT LESS THAN FROM MARKETING DEPARTMENT MAXIMUM SALARY
WITH AVGIT AS (
		SELECT AVG(SALARY) AS SAL_IT
		FROM EMPLOYEES
		WHERE DEPARTMENT_ID = 60 -- IT
	), 
    MAXMKT AS (
		SELECT MAX(SALARY) AS SAL_MKT
		FROM EMPLOYEES
		WHERE DEPARTMENT_ID = 20 -- MARKETING
    )
    
SELECT *
FROM EMPLOYEES
WHERE SALARY > (SELECT SAL_IT FROM AVGIT) AND SALARY < (SELECT SAL_MKT FROM MAXMKT);