SELECT *
FROM EMPLOYEES
WHERE DEPARTMENT_ID = 20;

SELECT DEPARTMENT_ID, MAX(SALARY)
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID;

SELECT DEPARTMENT_ID, COUNT(*)
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID;

-- HAVING
SELECT DEPARTMENT_ID, AVG(SALARY) AS sal
FROM EMPLOYEES
WHERE DEPARTMENT_ID <> 20
GROUP BY DEPARTMENT_ID
HAVING sal > 5000;

