-- ADD New Column
ALTER TABLE EMPLOYEES
ADD COLUMN EMAIL VARCHAR(50);

-- DROP COLUMN
ALTER TABLE EMPLOYEES
DROP COLUMN SALARY;

-- MODIFY COLUMN DATA TYPE
ALTER TABLE EMPLOYEES
MODIFY COLUMN EMAIL VARCHAR(70);

-- CHANGE COLUMN -> NAME
-- RENAME TO -> CHANGE TABLE NAME
-- ADD INDEX / ADD PRIMARY KEY
-- DROP INDEX / DROP PRIMARY KEY