-- 1. Show the employee names and corresponding job_titles using JOIN query

SELECT * FROM EMPLOYEES;
SELECT * FROM JOBS;

SELECT EMPLOYEES.FIRST_NAME, EMPLOYEES.LAST_NAME, JOBS.JOB_TITLE
FROM EMPLOYEES 
	JOIN JOBS
		ON EMPLOYEES.JOB_ID = JOBS.JOB_ID;