CREATE TABLE STUDENTS(
	STUDENT_ID INT PRIMARY KEY,
    NAME VARCHAR(50),
    AGE INT
);

SELECT * FROM STUDENTS;

-- COMPOSITE PRIMARY KEY
CREATE TABLE ORDERS(
	ORDER_ID INT,
    PRODUCT_ID INT,
    PRIMARY KEY(ORDER_ID, PRODUCT_ID)
);

SELECT * FROM ORDERS;

CREATE TABLE ENROLLMENTS(
	ENROLLMENT_ID INT PRIMARY KEY,
    STUDENT_ID INT,
    COURSE_ID INT,
    
    FOREIGN KEY(STUDENT_ID) REFERENCES STUDENTS(STUDENT_ID)
);

SELECT * FROM ENROLLMENTS;